---PROCEDIMIENTO PARA ASIGNACION DE PRODUCTOS AL CLIENTE
CREATE PROCEDURE DBO.SP_ASOCIAR_PRODUCTOS_CLIENTES  
	@ID_CLIENTE INT ,
	@ID_PRODUCTO INT 
AS 
BEGIN TRY
    BEGIN TRANSACTION
INSERT INTO FAVORITOS (CLIENTE,PRODUCTO)
SELECT @ID_CLIENTE,PT.ID 
FROM PRODUCTOS PT
WHERE PT.ID = @ID_PRODUCTO;

    COMMIT TRAN -- Transaction Success!
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRAN --RollBack in case of Error

    -- <EDIT>: From SQL2008 on, you must raise error messages as follows:
    DECLARE @ErrorMessage NVARCHAR(4000);  
    DECLARE @ErrorSeverity INT;  
    DECLARE @ErrorState INT;  

    SELECT   
       @ErrorMessage = ERROR_MESSAGE(),  
       @ErrorSeverity = ERROR_SEVERITY(),  
       @ErrorState = ERROR_STATE();  

    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);  
    -- </EDIT>
END CATCH



---ASIGNAR PRODUCTO-CLIENTE
EXEC DBO.SP_ASOCIAR_PRODUCTOS_CLIENTES
	@ID_CLIENTE= 2,
	@ID_PRODUCTO=3;



---CONSULTA FAVORITOS-CLIENTE
SELECT C.P_DOCUMENTO,C.NOMBRE,C.APELLIDO,P.PRODUCTO,COUNT(F.PRODUCTO) AS CANTIDAD_PRODUCTO
FROM clientes C
JOIN favoritos F ON C.id = F.cliente
JOIN productos P ON P.id=F.producto
GROUP BY C.P_DOCUMENTO,C.NOMBRE,C.APELLIDO,P.PRODUCTO
HAVING COUNT(F.producto)>1; 