---PROCEDIMIENTO PARA AGREGAR DIRECCIONES DEL CLIENTE POR DOCUMENTO

CREATE PROCEDURE DBO.SP_AGREGAR_DIRECCIONES  
	@P_DOCUMENTO NVARCHAR(10),
	@DIRECCION NVARCHAR(60),
	@PAIS NVARCHAR(50),
	@CIUDAD NVARCHAR(50),
	@CODIGO_POSTAL NVARCHAR(10)
AS 
BEGIN 
DECLARE @ID_CLIENTE INT;
	 SET NOCOUNT ON 
SELECT @ID_CLIENTE= C.ID  FROM CLIENTES C  WHERE C.P_DOCUMENTO = @P_DOCUMENTO;
	 INSERT INTO DBO.DIRECCIONES
		  (                    
			DIRECCION          ,
			PAIS               ,
			CIUDAD			   ,
			CODIGO_POSTAL      ,
			CLIENTE
		  ) 
	 VALUES 
		  ( 
			@DIRECCION,
			@PAIS,
			@CIUDAD,
			@CODIGO_POSTAL,
			@ID_CLIENTE
		  ) 
		  
END 



---PRUEBA DE PROCEDURE AGREGAR DIRECCIONES
EXEC DBO.SP_AGREGAR_DIRECCIONES
	@P_DOCUMENTO= '0011111111',
	@DIRECCION='DIRECCION 2 DEL CLIENTE PRUEBA1',
	@PAIS ='NADIE SABE.',
	@CIUDAD ='SANTO DOMINGO',
	@CODIGO_POSTAL=15801


---CONSULTA DIRECCIONES
SELECT * FROM DIRECCIONES;
--CONSULTAR CLIENTES CON MAS DE UNA DIRECCION
SELECT C.P_DOCUMENTO,C.NOMBRE,C.APELLIDO,COUNT(D.CLIENTE) AS CANTIDAD_DIRECCIONES
FROM CLIENTES C
JOIN DIRECCIONES D ON C.ID=D.CLIENTE
GROUP BY C.P_DOCUMENTO,C.NOMBRE,C.APELLIDO
HAVING COUNT(D.CLIENTE)>1; 